// modules/angular-app/src/app/app.component.ts
import { Component } from '@angular/core'

@Component({
  selector: 'app-root',
  template: `
    <!--The content below is only a placeholder and can be replaced.-->
    <div style="text-align:center" class="content">
      <h1>Welcome to {{ title }}!</h1>
      <img
        width="300"
        alt="Angular Logo"
        src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAyNTAgMjUwIj4KICAgIDxwYXRoIGZpbGw9IiNERDAwMzEiIGQ9Ik0xMjUgMzBMMzEuOSA2My4ybDE0LjIgMTIzLjFMMTI1IDIzMGw3OC45LTQzLjcgMTQuMi0xMjMuMXoiIC8+CiAgICA8cGF0aCBmaWxsPSIjQzMwMDJGIiBkPSJNMTI1IDMwdjIyLjItLjFWMjMwbDc4LjktNDMuNyAxNC4yLTEyMy4xTDEyNSAzMHoiIC8+CiAgICA8cGF0aCAgZmlsbD0iI0ZGRkZGRiIgZD0iTTEyNSA1Mi4xTDY2LjggMTgyLjZoMjEuN2wxMS43LTI5LjJoNDkuNGwxMS43IDI5LjJIMTgzTDEyNSA1Mi4xem0xNyA4My4zaC0zNGwxNy00MC45IDE3IDQwLjl6IiAvPgogIDwvc3ZnPg=="
      />
    </div>
    <div style="text-align:center" class="content">
      <ds-button raised>DS Button</ds-button>
      <div>
        <label style="display: inline-flex; align-items: center;">
          <ds-checkbox raised></ds-checkbox>
          DS Checkbox
        </label>
      </div>
    </div>
  `,
  styles: []
})
export class AppComponent {
  title = 'Angular App'
}

// modules/react-app/src/App.tsx
import React from 'react'
import logo from './logo.svg'
import './App.css'
import '@ds/components'
import Button from './components/Button'
import Checkbox from './components/Checkbox'
import { css } from 'emotion'

const App: React.FC = () => {
  return (
    <div className="App">
      <header className="App-header">
        <img src={logo} className="App-logo" alt="logo" />
      </header>
      <h1>Welcome to React</h1>
      <div className={spaceClass}>
        <Button raised onClick={() => console.log('clicked')}>
          Ds Button
        </Button>
      </div>
      <div className={spaceClass}>
        <ds-button raised onClick={() => console.log('clicked')}>
          DS Button
        </ds-button>
      </div>

      <div>
        <label
          className={css`
            display: inline-flex;
            align-items: center;
          `}>
          <Checkbox /> Check me
        </label>
      </div>
    </div>
  )
}

export default App

const spaceClass = css`
  margin: 5px;
`
